'use strict';

// Typed dependencies (BLUEPRINT §5, CLI.md M4; dx-01, crit-08, life:corr-19).
// Writes src/shared/LorenTypes.luau and the server-only src/server/LorenServerTypes.luau from the
// modules the runtime registers: the direct children of Services/ and Controllers/ (X.luau, X.lua,
// or a folder with init.luau / init.lua / .src.luau). Both files hold only types and end with
// `return table.freeze({})`; neither requires a Service or Controller, so no require cycles.

const fs = require('fs');
const path = require('path');
const { FOLDERS, TYPES_FILE, SERVER_TYPES_FILE, IDENTIFIER, LUAU_KEYWORDS } = require('./constants');
const { readText, readTextIfExists, writeText, normalizeEol, isDir, isFile, rel } = require('./fsutil');
const { analyzeLuau, isNetworked, projectLayout } = require('./lint');

const FOLDER_SOURCES = ['init.luau', 'init.lua', '.src.luau', '.src.lua'];

const byCodeUnit = (a, b) => (a < b ? -1 : a > b ? 1 : 0);

// name -> source file of each ModuleScript directly inside `dir` (Scripts and plain folders skipped).
function listModules(dir) {
	let entries;
	try {
		entries = fs.readdirSync(dir, { withFileTypes: true });
	} catch {
		return new Map();
	}
	const found = new Map();
	const add = (name, file) => {
		if (!found.has(name)) found.set(name, file); // X.luau and X.lua: Rojo refuses; keep the first
	};
	for (const e of entries.sort((a, b) => byCodeUnit(a.name, b.name))) {
		const full = path.join(dir, e.name);
		const directory = e.isDirectory() || (e.isSymbolicLink() && isDir(full));
		if (directory) {
			const source = FOLDER_SOURCES.map((f) => path.join(full, f)).find(isFile);
			if (source) add(e.name, source);
			continue;
		}
		const m = /^(.+)\.(luau|lua)$/i.exec(e.name);
		if (!m || !isFile(full)) continue;
		const base = m[1];
		if (/\.(server|client|local|legacy|plugin)$/i.test(base)) continue; // Script / LocalScript (Script Sync adds .local etc.)
		if (base === 'init' || base === '.src') continue; // the folder's own source, not a child
		add(base, full);
	}
	return found;
}

function luauString(s) {
	return `"${String(s)
		.replace(/\\/g, '\\\\')
		.replace(/"/g, '\\"')
		.replace(/\n/g, '\\n')
		.replace(/\r/g, '\\r')
		// three digits, so a digit after the escape is not read as part of it ("\1" .. "2" is not "\12")
		.replace(/[\x00-\x1f\x7f]/g, (c) => `\\${String(c.charCodeAt(0)).padStart(3, '0')}`)}"`;
}

const keyOf = (name) => (IDENTIFIER.test(name) && !LUAU_KEYWORDS.has(name) ? name : `[${luauString(name)}]`);

function unionType(alias, names) {
	if (names.length === 0) return `export type ${alias} = string -- none yet`;
	const one = `export type ${alias} = ${names.map(luauString).join(' | ')}`;
	if (one.length <= 100) return one;
	return `export type ${alias} =\n\t${names.map(luauString).join('\n\t| ')}`;
}

function keyedType(alias, entries) {
	if (entries.length === 0) return `export type ${alias} = { [string]: any } -- none yet`;
	const lines = entries.map(([name, type, note]) => `\t${keyOf(name)}: ${type},${note ? ` -- ${note}` : ''}`);
	return `export type ${alias} = {\n${lines.join('\n')}\n}`;
}

const HEADER = '-- AUTO-GENERATED by the Loren CLI (loren refresh, make, inject and update rewrite it). Do not edit.';

// Mirrors Loren's runtime types (LorenRuntime.Types) so this file needs no require.
const PROXY_TYPES = `-- What a Controller gets for a networked Service (the same shape as Loren's ServiceProxy).
export type Connection = {
	Connected: boolean,
	Disconnect: (...any) -> (),
	Destroy: (...any) -> (),
}

export type ClientSignal = {
	Connect: (self: ClientSignal, fn: (...any) -> ()) -> Connection,
	Once: (self: ClientSignal, fn: (...any) -> ()) -> Connection,
	Wait: (self: ClientSignal) -> ...any,
	DisconnectAll: (self: ClientSignal) -> (),
}

export type ClientEvent = {
	Fire: (self: ClientEvent, ...any) -> (),
}

export type ServiceProxy = {
	Signals: { [string]: ClientSignal },
	ClientEvents: { [string]: ClientEvent },
	Try: { [string]: any },
	[string]: any,
}`;

function sharedSource({ services, controllers, networked }) {
	const controllerSet = new Set(controllers);
	const clientDeps = [...new Set([...controllers, ...networked])].sort(byCodeUnit).map((name) => {
		const isController = controllerSet.has(name);
		const isService = networked.includes(name);
		if (isController && isService) return [name, 'any', 'a Controller and a networked Service: Loren refuses this at boot, rename one'];
		return [name, isService ? 'ServiceProxy' : 'any'];
	});
	return [
		'--!strict',
		HEADER,
		'--[[',
		'\tService and Controller names for Dependencies: autocomplete and typo checks. Values stay loose.',
		'\tController: Dependencies = { "Name" } :: { Types.ClientDependencyName },',
		'\t            local deps: Types.ClientDeps = self.Dependencies :: any',
		'\tService:    the same with ServerScriptService.Server.LorenServerTypes (ServiceName, ServerDeps).',
		'\tNetworkedServiceName: Services with Client methods, Signals, ClientEvents or a Spec.',
		']]',
		'',
		unionType('ServiceName', services),
		unionType('ControllerName', controllers),
		unionType('NetworkedServiceName', networked),
		'export type ClientDependencyName = ControllerName | NetworkedServiceName',
		'',
		PROXY_TYPES,
		'',
		keyedType('ClientDeps', clientDeps),
		'',
		keyedType('ServerDeps', services.map((name) => [name, 'any'])),
		'',
		'return table.freeze({})',
		'',
	].join('\n');
}

function serverSource({ services, networked }) {
	return [
		'--!strict',
		HEADER,
		'--[[',
		'\tServer only: every Service, including the ones clients never see.',
		'\tService: Dependencies = { "Name" } :: { ServerTypes.ServiceName },',
		'\t         local deps: ServerTypes.ServerDeps = self.Dependencies :: any',
		']]',
		'',
		unionType('ServiceName', services),
		unionType('NetworkedServiceName', networked),
		'',
		keyedType('ServerDeps', services.map((name) => [name, 'any'])),
		'',
		'return table.freeze({})',
		'',
	].join('\n');
}

// What the generated files would list: { services, controllers, networked } (sorted names).
// Folders: the options, else default.project.json's tree, else the scaffold's defaults.
function dirsOf(root, opts) {
	const layout = opts.sharedDir && opts.serverDir && opts.clientDir ? null : projectLayout(root);
	return {
		shared: opts.sharedDir || layout.shared,
		server: opts.serverDir || layout.server,
		client: opts.clientDir || layout.client,
	};
}

function collectNames(root, opts = {}) {
	const dirs = dirsOf(root, opts);
	const serverDir = path.join(root, dirs.server);
	const clientDir = path.join(root, dirs.client);
	const serviceMods = listModules(path.join(serverDir, FOLDERS.services));
	const controllerMods = listModules(path.join(clientDir, FOLDERS.controllers));
	const networked = [];
	for (const [name, file] of serviceMods) {
		try {
			if (isNetworked(analyzeLuau(readText(file)))) networked.push(name);
		} catch (err) {
			if (opts.log && opts.log.warn) opts.log.warn(`Could not read ${rel(root, file)} for types: ${err.message}`);
		}
	}
	return {
		services: [...serviceMods.keys()].sort(byCodeUnit),
		controllers: [...controllerMods.keys()].sort(byCodeUnit),
		networked: networked.sort(byCodeUnit),
	};
}

// generateTypes(root, { sharedDir, serverDir, clientDir, dryRun, log })
// -> { written, planned, unchanged, files, names }. `written`: the files it wrote (absolute paths);
// with dryRun nothing is written and `planned` lists what would change. Folders not given come from
// default.project.json. The server file is only written when the server folder exists.
function generateTypes(root, opts = {}) {
	const dirs = dirsOf(root, opts);
	const names = collectNames(root, { ...opts, sharedDir: dirs.shared, serverDir: dirs.server, clientDir: dirs.client });
	const sharedDir = path.join(root, dirs.shared);
	const serverDir = path.join(root, dirs.server);
	const files = { [path.join(sharedDir, TYPES_FILE)]: sharedSource(names) };
	if (isDir(serverDir)) files[path.join(serverDir, SERVER_TYPES_FILE)] = serverSource(names);

	const written = [];
	const planned = [];
	const unchanged = [];
	for (const [file, text] of Object.entries(files)) {
		const current = readTextIfExists(file);
		if (current !== null && normalizeEol(current) === text) {
			unchanged.push(file);
			continue;
		}
		planned.push(file);
		if (!opts.dryRun) {
			writeText(file, text);
			written.push(file);
		}
	}
	return { written, planned, unchanged, files, names };
}

module.exports = { generateTypes, collectNames, listModules, sharedSource, serverSource };
